window.DocumentosAEB = window.DocumentosAEB || {};
window.DocumentosAEB.gerarAditivoTransporte = function(dados) {
  return {
    content: [
      { text: 'ADITIVO CONTRATUAL – TRANSPORTE ESTUDANTIL (REGRAS OPERACIONAIS E FINANCEIRAS)\nPRESTAÇÃO DE SERVIÇO | 2º SEMESTRE/2026', style: 'header', alignment: 'center', bold: true, margin: [0, 0, 0, 15] },
      { text: 'O presente ADITIVO CONTRATUAL integra e complementa o Contrato-base de Adesão à AEB, disciplinando especificamente o serviço acessório e facultativo de transporte estudantil, nos termos do Estatuto da Associação. Ao aderir a este Aditivo, o(a) ASSOCIADO(A) manifesta ciência e concordância com as condições abaixo, sem prejuízo das normas estatutárias.', alignment: 'justify', margin: [0, 0, 0, 15] },
      { text: 'CLÁUSULA 1ª – OBJETO DO ADITIVO (TRANSPORTE): O objetivo do presente Aditivo é regular as relações entre a AEB e o(a) ASSOCIADO(A) quanto à utilização do transporte estudantil administrado pela Associação, para atendimento às instituições de ensino das cidades de Franca – SP e Ribeirão Preto – SP, bem como estabelecer regras operacionais e financeiras para sua prestação.\nParágrafo único: Refere-se a estudantes, para fins deste Aditivo, alunos universitários ou alunos de cursos técnicos profissionalizantes presenciais reconhecidos pelo MEC. Poderá haver extensão do transporte a outras categorias estudantis, desde que haja disponibilidade e que tal medida se mostre oportuna e conveniente aos associados(as) e à Diretoria, respeitado o Estatuto.\n§1º – Natureza da atuação da AEB: A AEB atua exclusivamente na administração, organização e intermediação do transporte estudantil, não sendo a prestadora direta do serviço de transporte, o qual é realizado por empresa(s) terceirizada(s) regularmente contratada(s), responsável(is) pela execução do serviço.', alignment: 'justify', margin: [0, 0, 0, 10] },
      { text: 'CLÁUSULA 2ª – PLANEJAMENTO, CALENDÁRIO E LIMITES DO SERVIÇO: Cabe à AEB o planejamento do itinerário, a marcação das atividades extraescolares quando aplicável e a fixação de providências operacionais necessárias à execução do transporte, observadas as orientações estatutárias.\n§1º – Caso não estejam programadas no calendário da AEB, não estão incluídas neste Aditivo semanas de recuperação, reforço, provas substitutivas, adaptação, exames, segunda época, semanas culturais, reciclagem, atividade prática, bem como quaisquer outras atividades de extensão.\n§2º – O transporte poderá ser suspenso em caso fortuito, força maior ou por determinação do Poder Público, não gerando responsabilidade direta à AEB pela execução do serviço, sem prejuízo das medidas administrativas e organizacionais que lhe competem.', alignment: 'justify', margin: [0, 0, 0, 10] },
      { text: 'CLÁUSULA 3ª – VIGÊNCIA DO TRANSPORTE: Este Aditivo tem validade durante o período compreendido entre 01 de julho de 2026 e 31 de dezembro de 2026, ressalvadas disposições em contrário, podendo ser prorrogado por meio de novo aditivo, com aceite eletrônico ou físico, que determinará seu novo prazo de validade.', alignment: 'justify', margin: [0, 0, 0, 10] },
      { text: 'CLÁUSULA 4ª – VALORES, COBRANÇA E PRESTAÇÃO DE CONTAS (TRANSPORTE): Pelos serviços de transporte estudantil administrados pela AEB, o(a) ASSOCIADO(A) pagará o valor mensal de R$ 480,00 (quatrocentos e oitenta reais), correspondente aos custos operacionais do serviço.\n§1º – Será concedido desconto por pontualidade no valor de R$10,00 (dez reais), aplicável exclusivamente aos pagamentos realizados até a data de vencimento, reduzindo o valor devido para R$470,00 (quatrocentos e setenta reais).\n§2º – O desconto por pontualidade não é cumulativo com quaisquer outros benefícios ou abatimentos, sendo aplicado de forma única por período de cobrança.\n§3º – O não pagamento até a data de vencimento implica na perda automática do desconto por pontualidade, permanecendo devido o valor integral do serviço de transporte, sem prejuízo dos encargos moratórios e demais medidas previstas no Estatuto e neste Aditivo.\n§4º – Transparência: A AEB divulgará previamente aos associados(as), por seus canais oficiais, os valores aplicáveis a cada período e/ou rota.\n§5º – O não comparecimento do(a) ASSOCIADO(A) ao transporte não exime o pagamento das mensalidades devidas, uma vez que o valor corresponde ao rateio do custo de disponibilidade do transporte fretado, contratado por vaga e independentemente da frequência individual de embarque.\n§6º – A adesão ao transporte e a manutenção deste Aditivo poderão estar condicionadas ao deferimento pela Diretoria da AEB, após certificação pela Tesouraria de que o(a) contratante está quite com suas obrigações anteriormente assumidas.\n§7º – O valor do transporte previsto nesta cláusula inclui a taxa associativa devida à Associação, não sendo esta cobrada separadamente durante a vigência do presente Aditivo.\n§8º – Os valores do transporte poderão ser revistos pela AEB em razão de alterações nos custos operacionais do serviço, nos termos do Estatuto e das condições deste Aditivo.', alignment: 'justify', margin: [0, 0, 0, 10] },
      { text: 'CLÁUSULA 5ª – ATRASO E ACRÉSCIMOS FINANCEIROS (TRANSPORTE): Havendo atraso no pagamento de cada mensalidade do transporte, o(a) ASSOCIADO(A) pagará, além do principal, os acréscimos abaixo, sem prejuízo da aplicação das medidas administrativas e disciplinares previstas no Estatuto (advertência, multa, suspensão, exclusão e demais), quando cabíveis.\nI – Multa fixa, como pena por atraso, de 2% (dois por cento) do principal, incidente a partir do dia posterior ao do vencimento.\nII – Juros de mora de 1% (um por cento) do valor principal, por mês.\n§1º – Além dos acréscimos financeiros, o(a) ASSOCIADO(A) poderá ter suspendido o direito de embarque após 15 (quinze) dias de atraso, como medida de natureza operacional, nos termos do Estatuto da AEB.\n§2º – Permanecendo a inadimplência por período superior a 30 (trinta) dias, o(a) associado(a) poderá ser submetido(a) aos procedimentos estatutários aplicáveis, inclusive quanto à exclusão do quadro social, garantidos contraditório e ampla defesa, sem prejuízo das medidas de cobrança cabíveis. A exclusão, quando aplicável, decorre do Estatuto e não dispensa a quitação das obrigações assumidas.\n§3º – A inscrição do nome do(a) associado(a) em cadastros de proteção ao crédito e/ou o protesto de títulos somente poderá ocorrer após prévia notificação, por meio idôneo, assegurando prazo razoável para regularização ou impugnação do débito, devendo a obrigação ser líquida, certa e exigível, nos termos da legislação vigente.', alignment: 'justify', margin: [0, 0, 0, 10] },
      { text: 'CLÁUSULA 5.1ª – TAXA DE RATEIO DE INADIMPLÊNCIA (TRI) – TRANSPORTE: É assegurada a cobrança da respectiva Taxa de Rateio de Inadimplência (TRI), de forma excepcional, temporária e justificada, destinada exclusivamente a cobrir prejuízos financeiros decorrentes da inadimplência quando esta comprometer a continuidade do transporte estudantil, conforme previsto no Estatuto.\n§1º – A instituição da Taxa de Rateio de Inadimplência (TRI) dependerá de deliberação formal da Diretoria, devidamente fundamentada, devendo conter: I – memória de cálculo detalhada; II – indicação expressa do período de incidência; III – valor máximo ou critério objetivo de limitação; IV – justificativa da necessidade para manutenção do serviço; V – comunicação prévia aos associados(as); VI – fiscalização pelo Conselho Fiscal.\n§2º – A TRI consistirá em valor adicional aplicado às mensalidades dos associados adimplentes, observados os limites, critérios objetivos e o período de incidência fixados na deliberação da Diretoria, com fiscalização do Conselho Fiscal.\n§3º – Eventual recuperação de valores inadimplidos que tenham ensejado a cobrança da TRI poderá implicar revisão, compensação ou abatimento proporcional aos associados(as) que suportaram o rateio, conforme deliberação da Diretoria e controle do Conselho Fiscal.\n§4º – A cobrança da TRI terá prazo determinado e observará o período de incidência definido na deliberação da Diretoria, sendo mantida apenas enquanto persistirem os pressupostos que justificaram sua instituição.\n§5º – A adoção da TRI não exclui a prerrogativa e a obrigação da AEB de adotar as medidas extrajudiciais e judiciais cabíveis para cobrança dos valores em atraso, devendo sua instituição, arrecadação, destinação e eventual compensação constar da prestação de contas submetida aos órgãos competentes, nos termos do Estatuto.', alignment: 'justify', margin: [0, 0, 0, 10] },
      { text: 'CLÁUSULA 5.2ª – DA RESPONSABILIDADE PELO TRANSPORTE: A responsabilidade da AEB limita-se aos atos inerentes à sua atuação administrativa, especialmente no que se refere à organização, planejamento, comunicação e fiscalização razoável do serviço, sem prejuízo da responsabilização direta da empresa transportadora por falhas na execução do transporte.', alignment: 'justify', margin: [0, 0, 0, 10] },
      { text: 'CLÁUSULA 6ª – DIREITOS E DEVERES NO TRANSPORTE: Ao utilizar o transporte, o(a) ASSOCIADO(A) deve respeitar as leis cíveis e penais e, em especial, as normas de trânsito, utilizando-se obrigatoriamente dos equipamentos de segurança, como cinto de segurança para passageiros, sob pena de responsabilização por desrespeito às normas legais, inclusive ressarcindo as partes apenadas.\nParágrafo único – Os demais direitos e deveres aplicáveis ao(à) associado(a), inclusive penalidades e recursos, estão previstos no Estatuto da AEB e nos regulamentos internos pertinentes.', alignment: 'justify', margin: [0, 0, 0, 10] },
      { text: 'CLÁUSULA 7ª – CANCELAMENTO E RESCISÃO DO TRANSPORTE: O(a) ASSOCIADO(A) poderá solicitar o cancelamento e/ou a rescisão deste Aditivo (serviço de transporte) mediante requerimento formal, com aviso prévio mínimo de 15 (quinze) dias, observadas as condições estatutárias e a quitação de eventuais obrigações financeiras anteriormente assumidas, inclusive as relacionadas ao transporte.\nParágrafo único – O não cumprimento do prazo de aviso prévio e/ou a ausência de comunicação formal do cancelamento/rescisão poderá implicar na cobrança das mensalidades correspondentes ao período necessário para sua efetivação, em razão de procedimentos administrativos, operacionais e compromissos previamente assumidos pela Associação, permanecendo devidas as obrigações vencidas ou vincendas até a data de efetiva formalização e processamento do pedido.\n§1º – Para fins de organização e encerramento do serviço, será devida a mensalidade do transporte até a data de cessação do serviço, limitada ao período correspondente ao aviso prévio não observado, vedada a cobrança cumulativa ou desproporcional.', alignment: 'justify', margin: [0, 0, 0, 10] },
      { text: 'CLÁUSULA 8ª – CARTEIRA/IDENTIFICAÇÃO PARA EMBARQUE: A carteira de identificação para o transporte é de inteira responsabilidade do(a) ASSOCIADO(A), sendo nominal e intransferível.\n§1º – Só será permitido o embarque do(a) ASSOCIADO(A) para transporte com a apresentação de sua carteira de identificação emitida pela AEB.\n§2º – A não apresentação da carteira de identificação exime a responsabilidade do representante do ônibus e da AEB caso o(a) ASSOCIADO(A) não esteja presente no momento do embarque (retorno) e, porventura, venha a permanecer na cidade de sua instituição de ensino.\n§3º – Será cobrada taxa de R$ 5,00 (cinco reais) para a confecção de 2ª via da carteira de identificação, no caso de perda ou extravio, devendo o(a) ASSOCIADO(A) comunicar tal fato imediatamente à AEB.', alignment: 'justify', margin: [0, 0, 0, 10] },
      { text: 'CLÁUSULA 9ª – PENALIDADES E MEDIDAS OPERACIONAIS NO TRANSPORTE: Além de acatar o Estatuto da AEB, o(a) ASSOCIADO(A) se obriga a zelar pelos bens patrimoniais colocados à sua disposição (inclusive veículos), bem como pelos pertences particulares de colegas, responsabilizando-se por danos que venha causar, seja com dolo e/ou culpa.\n§1º – O(a) ASSOCIADO(A) que causar qualquer tipo de dano poderá ser impedido(a) de embarcar até o total pagamento/ressarcimento dos prejuízos apurados.\n§2º – O(a) ASSOCIADO(A) autoriza que, em caso de inadimplemento e/ou por razões de segurança e organização do serviço, a AEB adote medidas administrativas operacionais previstas no Estatuto, incluindo suspensão do direito de embarque, exclusão de grupos oficiais de comunicação e retirada/alteração de ponto de embarque/desembarque, observados os princípios da razoabilidade e da publicidade.', alignment: 'justify', margin: [0, 0, 0, 10] },
      { text: 'CLÁUSULA 10ª – CARÁTER EXECUTIVO E DOCUMENTOS: O presente instrumento poderá constituir título executivo extrajudicial, nos termos do artigo 784, III, do Código de Processo Civil, desde que assinado pelas partes e por 2 (duas) testemunhas, ou por meio eletrônico com mecanismos que assegurem a autenticidade, integridade e validade jurídica da assinatura.\n§1º – O(a) ASSOCIADO(A) afirma dar por este, e na melhor forma de direito, o aceite característico dos títulos de crédito, para fins de eventual protesto, consoante as cláusulas deste Aditivo.\n§2º – As partes reconhecem que a AEB realiza a administração do transporte estudantil, sendo a execução do serviço de responsabilidade da empresa de transporte contratada, nos termos da legislação aplicável.\n§3º – Uma vez reconhecida a obrigação da AEB neste instrumento, qual seja: a administração do transporte coletivo de alunos para as cidades de Franca – SP e Ribeirão Preto – SP, fica pactuado que qualquer emissão de documentos para efeitos fiscais é de responsabilidade exclusiva da empresa de transporte, não caracterizando referido e eventual documento condição indispensável para efeitos de execução e/ou protesto.', alignment: 'justify', margin: [0, 0, 0, 10] },
      { text: 'CLÁUSULA 11ª – PROTEÇÃO DE DADOS PESSOAIS (LGPD): Os dados informados nesta ficha serão tratados pela AEB para fins de gestão associativa e operação do transporte, podendo ser compartilhados com a transportadora e o Município, nos termos da cláusula de Proteção de Dados do Contrato-Base e da Lei 13.709/2018.', alignment: 'justify', margin: [0, 0, 0, 10] },
      { text: 'CLÁUSULA 12ª – DISPOSIÇÕES GERAIS E FORO: Fica eleito o foro da Comarca de Batatais, Estado de São Paulo, por mais privilegiado que outro possa ser, para dirimir qualquer dúvida ou conflito de interesses oriundos deste Aditivo e do contrato-base.', alignment: 'justify', margin: [0, 0, 0, 10] },
      {
        unbreakable: true,
        stack: [
          { text: 'CLÁUSULA 13ª - ASSINATURA ELETRÔNICA E DISPENSA DE VIAS FÍSICAS: As Partes concordam que este instrumento será assinado de forma eletrônica, utilizando-se o portal gov.br (níveis Prata ou Ouro), nos termos do art. 10, § 2º, da Medida Provisória nº 2.200-2/2001 e da Lei nº 14.063/2020. E, por estarem assim justas e contratadas, declaram reconhecer expressamente a validade, integridade, autenticidade e eficácia jurídica do presente documento, bem como sua força executiva, o qual constituirá um único arquivo digital original para todos os fins de direito, dispensando-se a emissão ou assinatura de vias físicas.', alignment: 'justify', margin: [0, 0, 0, 80] },
          {
            columns: [
              { text: '_____________________________________\nAssociado(a)\n\nNOME: ' + (dados.isMaior ? dados.nome : '') + '\nRG/CIN: ' + (dados.isMaior ? (dados.rg || dados.cpf) : ''), alignment: 'center' },
              { text: '_____________________________________\nPai ou Responsável\n\nNOME: ' + (!dados.isMaior ? dados.nomeResp : '') + '\nRG/CIN: ' + (!dados.isMaior ? dados.rgResp : ''), alignment: 'center' }
            ]
          },
          { text: '_____________________________________\nAssociação dos Estudantes de Batatais', alignment: 'center', margin: [0, 30, 0, 0] }
        ]
      }
    ],
    defaultStyle: { fontSize: 10 }
  };
};
